/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class net_malhar_Main */

#ifndef _Included_net_malhar_Main
#define _Included_net_malhar_Main
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     net_malhar_Main
 * Method:    loadClasses
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_net_malhar_Main_loadClasses
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
